version: '3.9'

services:
  mongo:
    # Command to launch mongosh : 
    # docker run -it --network nosql-net --rm mongo mongosh --host mongo root
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    # Command to launch redis-cli :
    # docker run -it --network nosql-net --rm redis redis-cli -h redis
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

networks:
  default:
    name: nosql-net

volumes:
  mongo-data:
  redis-data: