version: '3.9'

services:
  # We will create the cluster using this command:
  # docker run -it --rm --network redis-net redis redis-cli -h redis0 --cluster create redis0:6379 redis1:6379 redis2:6379

  redis0:
    image: redis:7
    command: redis-server --cluster-enabled yes
    expose:
      - '6379'

  redis1:
    image: redis:7
    command: redis-server --cluster-enabled yes
    expose:
      - '6379'
  
  redis2:
    image: redis:7
    command: redis-server --cluster-enabled yes
    expose:
      - '6379'

networks:
  default:
    name: redis-net
