version: '3.9'

services:
  app:
    build: .
    container_name: c-app
    volumes:
      - .:/app

  db:
    image: mysql
    container_name: c-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql

volumes:
  db-data:
