CREATE DATABASE IF NOT EXISTS parking;
CREATE TABLE IF NOT EXISTS parking.vehicule (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    immatriculation VARCHAR(8),
    type tinyint,
    heureArrivee TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);